Update vmnamereservation.yml

diff --git a/.github/workflows/vmnamereservation.yml b/.github/workflows/vmnamereservation.yml
--- a/.github/workflows/vmnamereservation.yml
+++ b/.github/workflows/vmnamereservation.yml
@@ -15,38 +15,38 @@ jobs:
         pwd
   
 #    - name: Install required PowerShell modules
-#      shell: pwsh
+#     shell: pwsh
 #      run: |
 #        Set-PSRepository PSGallery -InstallationPolicy Trusted
 #        Install-Module -Name Az.Storage -Scope CurrentUser -Repository PSGallery
 
-#    - name: Download CSV
-#      run: |
-#        if curl -o csv\azurevmnames.csv https://villatestsa.blob.core.windows.net/azure-vmname/azurevmnames.csv; then
-#          echo "CSV download successful."
-#        else
-#          echo "CSV download failed."
-#          exit 1
-#        fi
+    - name: Download CSV
+      run: |
+        if curl -o /home/runner/work/AzureStuff/AzureStuff/azurevmnames.csv https://villatestsa.blob.core.windows.net/azure-vmname/azurevmnames.csv; then
+          echo "CSV download successful."
+        else
+          echo "CSV download failed."
+          exit 1
+        fi
 
-#   - name: Check CSV Location
-#     run: |
-#        find . -type f -name azurevmnames.csv
+    - name: Check CSV Location
+      run: |
+        find . -type f -name azurevmnames.csv
 
-#    - name: Check CSV File Size
-#      id: check-csv
-#      run: |
-#        if [ -s csv\azurevmnames.csv ]; then
-#          echo "CSV file is not empty."
-#        else
-#          echo "CSV file is empty."
-#          exit 1
-#        fi
+    - name: Check CSV File Size
+      id: check-csv
+      run: |
+        if [ -s csv\azurevmnames.csv ]; then
+          echo "CSV file is not empty."
+        else
+          echo "CSV file is empty."
+          exit 1
+        fi
 
-#    - name: Read CSV file content - Before PS
-#      id: Read-csv
-#      run: |
-#        cd /home/runner/work/AzureStuff/AzureStuff/VMNAMEReservation/csv && tail azurevmnames.csv
+    - name: Read CSV file content - Before PS
+      id: Read-csv
+      run: |
+        cd /home/runner/work/AzureStuff/AzureStuff && tail azurevmnames.csv
     
 #    - name: Run PS Script
 #      shell: pwsh
@@ -56,4 +56,4 @@ jobs:
 #    - name: Read CSV file content - After PS
 #      id: ReRead-Csv
 #      run: |
-#        cd /home/runner/work/AzureStuff/AzureStuff/VMNAMEReservation/csv && tail azurevmnames.csv
+#        cd /home/runner/work/AzureStuff/AzureStuff && tail azurevmnames.csv
