Update vmnamereservation.yml

diff --git a/.github/workflows/vmnamereservation.yml b/.github/workflows/vmnamereservation.yml
--- a/.github/workflows/vmnamereservation.yml
+++ b/.github/workflows/vmnamereservation.yml
@@ -12,7 +12,22 @@ jobs:
 
     - name: Download CSV
       run: |
-        curl -o csv\azurevmnames.csv https://github.com/VillaDaniele/AzureStuff/blob/main/VMNAMEReservation/csv/azurevmnames.csv
+        if curl -o csv\azurevmnames.csv https://github.com/VillaDaniele/AzureStuff/blob/main/VMNAMEReservation/csv/azurevmnames.csv; then
+          echo "CSV download successful."
+        else
+          echo "CSV download failed."
+          exit 1
+        fi
+
+    - name: Check CSV File Size
+      id: check-csv
+      run: |
+        if [ -s csv\azurevmnames.csv ]; then
+          echo "CSV file is not empty."
+        else
+          echo "CSV file is empty."
+          exit 1
+        fi
 
     - name: Run PS Script
       shell: pwsh
