Update vmnamereservation.yml

diff --git a/.github/workflows/vmnamereservation.yml b/.github/workflows/vmnamereservation.yml
--- a/.github/workflows/vmnamereservation.yml
+++ b/.github/workflows/vmnamereservation.yml
@@ -10,6 +10,15 @@ jobs:
     - name: Checkout Repository
       uses: actions/checkout@v4
 
+    - name: Download New CSV
+      run: |
+        if curl -o csv\azurevmnames.csv https://github.com/VillaDaniele/AzureStuff/blob/main/VMNAMEReservation/csv/azurevmnames.csv; then
+          echo "CSV download successful."
+        else
+          echo "CSV download failed."
+          exit 1
+        fi
+
     - name: Run PS Script
       shell: pwsh
       run: |
